# Generated by Django 5.1.2 on 2024-11-09 13:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категорію", "verbose_name_plural": "Категорії"},
        ),
        migrations.AlterModelOptions(
            name="expense",
            options={"verbose_name": "Витрату", "verbose_name_plural": "Витрати"},
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Назва категорії"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.FloatField(verbose_name="Сума"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(max_length=255, verbose_name="Категорія"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата"
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="description",
            field=models.TextField(verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Власник",
            ),
        ),
    ]
