# Generated by Django 5.1.2 on 2024-11-09 13:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Джерело надходження"
                    ),
                ),
            ],
            options={
                "verbose_name": "Джерело надходження",
                "verbose_name_plural": "Джерела надходження",
            },
        ),
        migrations.CreateModel(
            name="UserIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(verbose_name="Сума")),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата"
                    ),
                ),
                ("description", models.TextField(verbose_name="Опис")),
                (
                    "source",
                    models.CharField(
                        max_length=255, verbose_name="Джерело надходження"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Власник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Надходження",
                "verbose_name_plural": "Надходження",
            },
        ),
    ]
